services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
