services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mainframe
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # nats:
  #   image: nats:latest
  #   command: -js
  #   ports:
  #     - 4222:4222
  #     - 8222:8222
  #     - 6222:6222

  # nats-ui:
  #   image: ghcr.io/nats-nui/nui:latest
  #   ports:
  #     - 31311:31311
